/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management;

import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Properties;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author Jitender
 */
public class newguest extends javax.swing.JFrame {
String otp;
    /**
     * Creates new form newguest
     */
    public newguest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jotp = new javax.swing.JTextField();
        jname = new javax.swing.JTextField();
        jphone = new javax.swing.JTextField();
        jTextmail = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        val = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jadd = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("     Hotel Management System");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 90));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter OTP");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 140, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 140, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Phone");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 140, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Address");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 140, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Email");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 140, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Password");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 140, 40));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Reset");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 120, 40));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Verify OTP");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, 120, 40));

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Submit");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 120, 40));

        jotp.setBackground(new java.awt.Color(0, 0,0,80));
        jotp.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 180, 40));

        jname.setBackground(new java.awt.Color(0, 0,0,80));
        jname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 180, 40));

        jphone.setBackground(new java.awt.Color(0, 0,0,80));
        jphone.setForeground(new java.awt.Color(255, 255, 255));
        jphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jphoneKeyPressed(evt);
            }
        });
        getContentPane().add(jphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 180, 40));

        jTextmail.setBackground(new java.awt.Color(0, 0,0,80));
        jTextmail.setForeground(new java.awt.Color(255, 255, 255));
        jTextmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextmailKeyReleased(evt);
            }
        });
        getContentPane().add(jTextmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 180, 40));

        jpassword.setBackground(new java.awt.Color(0, 0,0,80));
        getContentPane().add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 180, 40));
        getContentPane().add(val, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 160, 40));

        jadd.setBackground(new java.awt.Color(0, 0,0,80));
        jadd.setColumns(20);
        jadd.setForeground(new java.awt.Color(255, 255, 255));
        jadd.setRows(5);
        jScrollPane1.setViewportView(jadd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/red1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void otpgenerte(){
         Random rand=new Random();
         otp=String.valueOf(rand.nextInt(999999));
        
        
                String email=jTextmail.getText();
                String message = "your otp is :- "+otp;
		String subject = "LPG Gas Pipe Connection";
		String to = email;
		String from = "anuj9896388147@gmail.com";
		
	sendEmail(message,subject,to,from);
//		sendAttach(message,subject,to,from);
	}

	//this is responsible to send the message with attachment
	private static void sendEmail(String message, String subject, String to, String from) {

		//Variable for gmail
		String host="smtp.gmail.com";
		
		//get the system properties
		Properties properties = System.getProperties();
		System.out.println("PROPERTIES "+properties);
		
		//setting important information to properties object
		
		//host set
		properties.put("mail.smtp.host", host);
		properties.put("mail.smtp.port","465");
		properties.put("mail.smtp.ssl.enable","true");
		properties.put("mail.smtp.auth","true");
		
		//Step 1: to get the session object..
		Session session=Session.getInstance(properties, new Authenticator() {
			@Override
			protected PasswordAuthentication getPasswordAuthentication() {				
				return new PasswordAuthentication("anuj9896388147@gmail.com","zdkpfmdqwzhxstkg");
			}			
		});
		
		session.setDebug(true);
		
		//Step 2 : compose the message [text,multi media]
		MimeMessage m = new MimeMessage(session);
		
		try {
		
		//from email
		m.setFrom(from);
		
		//adding recipient to message
		m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
		
		//adding subject to message
		m.setSubject(subject);
		m.setText(message);
		
		//step 3 
		Transport.send(m);
		System.out.println("send sucessfully .................");
		
		
		}catch (Exception e) {
			e.printStackTrace();
		}
    }
        
        //+==============================================================
        
        
        public void welcome_update(){
                String email=jTextmail.getText();
                String message = "Thanks for register on LPG Natural Gas pipe line\n"
                        + "We are providing the best natural gas service";
		String subject = "LPG Gas Pipe Connection";
		String to = email;
		String from = "anuj9896388147@gmail.com";
		
	sendemail(message,subject,to,from);
//		sendAttach(message,subject,to,from);
	}

	//this is responsible to send the message with attachment
	private static void sendemail(String message, String subject, String to, String from) {

		//Variable for gmail
		String host="smtp.gmail.com";
		
		//get the system properties
		Properties properties = System.getProperties();
		System.out.println("PROPERTIES "+properties);
		
		//setting important information to properties object
		
		//host set
		properties.put("mail.smtp.host", host);
		properties.put("mail.smtp.port","465");
		properties.put("mail.smtp.ssl.enable","true");
		properties.put("mail.smtp.auth","true");
		
		//Step 1: to get the session object..
		Session session=Session.getInstance(properties, new Authenticator() {
			@Override
			protected PasswordAuthentication getPasswordAuthentication() {				
				return new PasswordAuthentication("anuj9896388147@gmail.com","zdkpfmdqwzhxstkg");
			}			
		});
		
		session.setDebug(true);
		
		//Step 2 : compose the message [text,multi media]
		MimeMessage m = new MimeMessage(session);
		
		try {
		
		//from email
		m.setFrom(from);
		
		//adding recipient to message
		m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
		
		//adding subject to message
		m.setSubject(subject);
		m.setText(message);
		
		//step 3 
		Transport.send(m);
		//System.out.println("send sucessfully .................");
		
		
		}catch (Exception e) {
			e.printStackTrace();
		}
        }
        public void nul() {
        jname.setText(null);
        jphone.setText(null);       
        jadd.setText(null);
        jTextmail.setText(null);
        jpassword.setText(null);
        jotp.setText(null);
    }
        
        
        
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       guestlogin ad=new guestlogin();
               ad.setVisible(true);
               dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jphoneKeyPressed
        String phoneNumber = jphone.getText();
        //set length of the string
        int length = phoneNumber.length();
        char c = evt.getKeyChar();
        //check for number 0 to 9
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            //check for length of number is not greater than 10 digits
            if (length < 10) {
                jphone.setEditable(true);
            } else {
                //not editr if length is more than 10 digit
                jphone.setEditable(false);
            }
        } else {
            //now allow for key back space and delete
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                //allow edit
                jphone.setEditable(true);
            } else {
                jphone.setEditable(false);
            }
        }
    }//GEN-LAST:event_jphoneKeyPressed

    private void jTextmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextmailKeyReleased
         String pat = "^[a-zA-Z0-9]{2,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match = patt.matcher(jTextmail.getText());
        if (!match.matches()) {
            val.setText("enter email is wrong");
        } else {
            val.setText(null);
        }
    }//GEN-LAST:event_jTextmailKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String name = jname.getText();
        String contact = jphone.getText();       
        String adderss = jadd.getText();
        String mail = jTextmail.getText();
        String pass = jpassword.getText();
        String set1 = val.getText();

        if ("".equals(name) || "".equals(contact) || "".equals(adderss) || "".equals(mail) || "".equals(pass)) {
            JOptionPane.showConfirmDialog(this, "All fields are Mandotory");
        }
        else if (set1 != null) {
            JOptionPane.showConfirmDialog(this, "enter a valid email");
        } 
        else {
       otpgenerte();       
        JOptionPane.showMessageDialog(null, "otp is send succesfully on your register email");
           
        }       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String val=jotp.getText();
if("".equals(val)){
         JOptionPane.showMessageDialog(null, "You have not enter otp");
}
else{
    if(val.endsWith(otp))
        {

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "Anuj0806$");
                String sql = "insert into guest values(?,?,?,?,?)";               
                PreparedStatement ptst = conn.prepareStatement(sql);               
                ptst.setString(1, jname.getText());                                                            
                ptst.setString(2, jphone.getText());                              
                ptst.setString(3, jadd.getText());
                ptst.setString(4, jTextmail.getText());
                ptst.setString(5, jpassword.getText());
                
                ptst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Account create succesfully");
                conn.close();
                welcome_update();
                guestlogin ad = new guestlogin();
                ad.setVisible(true);
                dispose();
                

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Your email is already register in our system");
                nul();
            }

            //************************************************************************************************************************
//            try {
//                Class.forName("com.mysql.cj.jdbc.Driver");
//                java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gasconnection", "root", "Anuj0806$");
//                String sql = "insert into login values(?,?,?)";
//                PreparedStatement ptst = conn.prepareStatement(sql);
//               
//                ptst.setString(2, jTextmail.getText());
//                ptst.setString(3, jTextpassword.getText());
//                ptst.executeUpdate();
//
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
  
        }
            else{ 
            JOptionPane.showMessageDialog(null, "wrong otp");
            jotp.setText(null);
        }
}
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newguest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextmail;
    private javax.swing.JTextArea jadd;
    private javax.swing.JTextField jname;
    private javax.swing.JTextField jotp;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jphone;
    private javax.swing.JLabel val;
    // End of variables declaration//GEN-END:variables
}
